import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import StyledComponentsRegistry from './lib/registry';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Corsets',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <>
            <Header />
            {children}
          </>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
